---
- hosts: loadbalancer
  become: yes
  roles:
    - name: base
    - name: coredns
    - name: traefik
      # NOTE: I'm "abusing" the load balancer VM to collect Vault
      # audit logs just to avoid the need of another VM for this demo.
      #
      # OF COURSE AUDIT LOGS OF YOUR SECRET MANAGEMENT
      # *NEVER* BELONG ON AN OUTSIDE FACING MACHINE!
    - name: syslog-ng
      tags: ['syslog-ng']


- hosts: consul_nomad
  become: yes
  roles:
    - name: base
    - name: consul
    - name: jre
    - name: docker
      tags: ['docker']
    - name: syslog-ng
      tags: ['syslog-ng']
    - name: vault
      tags: ['vault']
    - name: nomad
      tags: ['nomad']

  post_tasks:
    - name: Disable systemd-resolved service
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      tags: ['always']

    - name: Set nameserver to localhost
      copy:
        content: "nameserver {{ loadbalancer_ip }}"
        dest: /etc/resolv.conf
        mode: 0644
      tags: ['always']

    - name: Restart Docker to pick up DNS change
      systemd:
        name: docker
        state: restarted
      tags: ['docker']
