---
- name: Create temporary download directory if it does not exist
  delegate_to: localhost
  run_once: true
  become: no
  file:
    path: "{{ playbook_dir }}/.ansible_download_cache"
    state: directory
    mode: 0755

- block:
    - name: Determine latest GitHub release (local)
      delegate_to: localhost
      become: false
      uri:
        url: "https://api.github.com/repos/hashicorp/nomad/releases"
        body_format: json
      register: _github_releases
      until: _github_releases.status == 200
      retries: 5

    - name: Set nomad_version
      set_fact: nomad_version="{{ _github_releases.json | json_query('[?prerelease==`false` && draft==`false`].tag_name') | community.general.version_sort | last | regex_replace('^v?(.*)$', '\\1') }}"

  when: (nomad_version is not defined) or (nomad_version == 'latest')
  run_once: true

- name: Download Nomad and verify SHA256 checksum
  delegate_to: localhost
  run_once: true
  become: no
  get_url:
    url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: "{{ playbook_dir }}/.ansible_download_cache/nomad_{{ nomad_version }}_linux_amd64.zip"
    checksum: "sha256:https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_SHA256SUMS"

- name: Extract Nomad
  unarchive:
    src: "{{ playbook_dir }}/.ansible_download_cache/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: /usr/bin

- name: Create nomad user
  user:
    name: nomad
    home: /etc/nomad.d
    system: yes
    shell: /usr/bin/false
    state: present

- name: Create data directory
  file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad
    mode: 0755

- name: Check if Nomad token for Vault exists
  delegate_to: localhost
  become: no
  stat: path="{{ vault_token_dir }}/nomad-token"
  register: _vault_nomad_token_file

- name: Load Nomad token
  no_log: yes
  set_fact: vault_nomad_token="{{ lookup('file', vault_token_dir + '/nomad-token') }}"
  when: _vault_nomad_token_file.stat.exists

- name: Copy config
  template:
    src: "nomad.hcl.j2"
    dest: "/etc/nomad.d/nomad.hcl"
    owner: nomad
    group: nomad
    mode: 0644

- name: Create jobs directory
  file:
    path: "/home/{{ ansible_ssh_user }}/nomad_jobs"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755

- name: Copy example jobs config
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_ssh_user }}/nomad_jobs/{{ item | basename }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644
  with_fileglob:
    - "{{ playbook_dir }}/nomad_jobs/*.nomad"

- name: Copy systemd service
  copy:
    src: "nomad.service"
    dest: "/etc/systemd/system/nomad.service"
    mode: 0644

- name: Start nomad service
  systemd:
    name: nomad
    state: restarted
    daemon_reload: yes
    enabled: yes
