---
- name: Update apt cache
  apt: update_cache=yes

- name: Install base dependencies
  package:
    name:
      - curl
      - dnsutils
      - jq
      - unzip
    state: present

- name: Disable Ubuntu motd-news
  lineinfile:
    dest: /etc/default/motd-news
    state: present
    regexp: '^ENABLED='
    line: 'ENABLED=0'
  when: ansible_distribution == 'Ubuntu'

